[package]
edition = "2021"
name = "submillisecond"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0"
http = "0.2.7"
http-body = "0.4"
httparse = "1.7.1"
httpdate = "1.0"
lunatic = "0.9.1"
mime = "0.3.16"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0"
askama = "0.11"
