[package]
edition = "2021"
name = "submillisecond"
version = "0.1.0"

[dependencies]
askama = "0.11"
http = "0.2.7"
httparse = "1.7.1"
lunatic = "0.9.1"
mime = "0.3.16"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0"
