[workspace]
members = [".", "submillisecond_core", "submillisecond_macros"]

[package]
edition = "2021"
name = "submillisecond"
version = "0.1.0"

[dependencies]
askama = "0.11"
headers = "0.3"
http = "0.2.7"
httparse = "1.7.1"
lunatic = "0.9.1"
mime = "0.3.16"
paste = "1.0"
percent-encoding = "2.1"
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0"
serde_urlencoded = "0.7"
submillisecond_core = {path = "submillisecond_core"}
submillisecond_macros = {path = "submillisecond_macros"}

[dev-dependencies]
base64 = "0.13.0"
lazy_static = "1.4.0"
matchit = "*"
ron = "0.7"
uuid = {version = "1.0.0", features = ["v4", "serde"]}
