[package]
name = "submillisecond_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
submillisecond_core = { path = "../submillisecond_core" }
syn = { version = "1.0", features = ["derive", "extra-traits", "full"] }
